In [22]:
import numpy as np

create 1D and 2D array

In [23]:
arr1=np.array([1,2,34,5])
arr1


array([ 1,  2, 34,  5])

In [24]:
arr2=np.array([[3,2,1],[23,4,1]])
arr2

array([[ 3,  2,  1],
       [23,  4,  1]])

create array with zeros

In [25]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

create a array with a particular number

In [26]:
n=np.full((2,2),9)
n

array([[9, 9],
       [9, 9]])

create a array within the range

arange has three atributes start_point, end_point and skip_value (default is 1)

In [27]:
n=np.arange(10,20)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
n=np.arange(20,30,2)
n

array([20, 22, 24, 26, 28])

initializing np array with random numbers


In [32]:
n=np.random.randint(20,30,20)
n

array([23, 21, 21, 26, 25, 26, 23, 29, 28, 20, 29, 21, 22, 24, 21, 28, 22,
       24, 23, 21])

shape of an array

In [33]:
n.shape

(20,)

In [34]:
n.shape=(10,2)
n

array([[23, 21],
       [21, 26],
       [25, 26],
       [23, 29],
       [28, 20],
       [29, 21],
       [22, 24],
       [21, 28],
       [22, 24],
       [23, 21]])

joining numpy arrays using vstack(),hstack() and column_stack()

vstack()

In [37]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

In [38]:
np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

hstack()

In [39]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6, 7, 8])

column_stack()

In [40]:
np.column_stack((arr1,arr2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

intersection and difference in numpy array


In [41]:
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,7,8])

In [43]:
np.intersect1d(arr1,arr2)

array([3, 4])

In [44]:
np.setdiff1d(arr1,arr2)

array([1, 2])

numpy array mathematics

In [48]:
np.sum([arr1,arr2])

32

axis =0 is along the column

In [49]:
np.sum([arr1,arr2],axis=0)

array([ 4,  6, 10, 12])

axis = 1 is along the row

In [50]:
np.sum([arr1,arr2],axis=1)

array([10, 22])

addition of a scalar to array


In [57]:
ar=np.array([12,13,15,14])
ar=ar+1
ar

array([13, 14, 16, 15])

in the same way we can do subtraction, multiplication and division

mean

In [58]:
np.mean(ar)


14.5

In [59]:
np.median(ar)

14.5

In [60]:
np.std(ar)

1.118033988749895

matrix numpy


In [64]:
#lets say n is the matrix
n=np.array([[1,2,3],[4,5,6],[3,5,7]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [3, 5, 7]])

matrix indexing
|(0,0),(0,1),(0,2)|
|(1,0),(1,1),(1,2)|
|(2,0),(2,1),(2,2)|

In [62]:
n[0,1]

2

In [63]:
n[:,0]

array([1, 4, 3])

In [65]:
n[0,:]

array([1, 2, 3])

transpose interchanges column into row

In [68]:
#example
np.transpose(n)

array([[1, 4, 3],
       [2, 5, 5],
       [3, 6, 7]])

matrix multiplication

In [69]:
n1=np.array([[9,8,7],[6,5,4],[3,2,1]])
n1
    

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

multiplication of two dimensional array is the dot product of those arrays

In [70]:
n.dot(n1)

array([[30, 24, 18],
       [84, 69, 54],
       [78, 63, 48]])

numpy save and load

In [71]:
np.save("n",n)

In [72]:
np.load("n.npy")

array([[1, 2, 3],
       [4, 5, 6],
       [3, 5, 7]])